CREATE TYPE iiz.call_direction AS ENUM ('inbound', 'outbound', 'internal');
CREATE TYPE iiz.call_status AS ENUM ('answered', 'missed', 'voicemail', 'in_progress', 'failed');
CREATE TYPE iiz.channel_type AS ENUM ('web_chat', 'sms', 'whatsapp');
CREATE TYPE iiz.user_role AS ENUM ('admin', 'agent', 'supervisor');
CREATE TYPE iiz.agent_status AS ENUM ('available', 'on_call', 'after_call_work', 'offline', 'break', 'dnd');
CREATE TYPE iiz.queue_strategy AS ENUM ('ring_all', 'round_robin', 'longest_idle', 'weighted');
CREATE TYPE iiz.monitor_mode AS ENUM ('listen', 'whisper', 'barge');
CREATE TYPE iiz.export_format AS ENUM ('csv', 'pdf', 'excel');
CREATE TYPE iiz.speaker_type AS ENUM ('agent', 'caller', 'system');
CREATE TYPE iiz.number_class AS ENUM ('local', 'toll_free');
CREATE TYPE iiz.number_type AS ENUM ('offsite_static', 'onsite_dynamic');
CREATE TYPE iiz.workflow_node_type AS ENUM ('event', 'condition', 'action');
CREATE TYPE iiz.sip_transport AS ENUM ('udp', 'tcp', 'tls', 'wss');
CREATE TYPE iiz.active_call_status AS ENUM ('ringing', 'active', 'on_hold', 'transferring', 'wrapping');
CREATE TYPE iiz.account_type AS ENUM ('agency', 'standard');
CREATE TYPE iiz.account_status AS ENUM ('active', 'suspended', 'closed');
CREATE TYPE iiz.summary_type AS ENUM ('classic', 'customer_success', 'key_insights', 'action_items', 'sentiment_analysis', 'lead_qualification', 'compliance_review', 'topic_classification', 'custom');
CREATE TYPE iiz.greeting_type AS ENUM ('audio', 'tts', 'default', 'none');
CREATE TYPE iiz.compliance_status AS ENUM ('draft', 'submitted', 'pending', 'in_progress', 'approved', 'rejected', 'suspended', 'expired', 'completed', 'not_started', 'not_applicable', 'not_registered');
CREATE TYPE iiz.attestation_level AS ENUM ('a', 'b', 'c');
